### ISSUE TITLE
代理已配置，提示错误SOCKSHTTPSConnectionPool(host='www.fanbus.us', port=443)

### ISSUE THREAD

**Issue by bravoleexin** [yoshiko2/Movie_Data_Capture#571]
具体日志如下：
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for [.\ipx-471-C.mp4], the number is [ipx-471]
[-]Connect retry 1/3
[-]SOCKSHTTPSConnectionPool(host='cn.airav.wiki', port=443): Max retries exceeded with url: /video/ipx-471 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))
[-]Connect retry 2/3
[-]SOCKSHTTPSConnectionPool(host='cn.airav.wiki', port=443): Max retries exceeded with url: /video/ipx-471 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))
[-]Connect retry 3/3
[-]SOCKSHTTPSConnectionPool(host='cn.airav.wiki', port=443): Max retries exceeded with url: /video/ipx-471 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))
[-]Connect Failed! Please check your Proxy or Network!

**Comment by cascadahk** [comment]
我本身不用牆翻也用不到
連接去不同的VPN也失敗

**Comment by Metalism666** [comment]
我也是一样的报错，梯子开全局模式也是不能用

**Comment by cascadahk** [comment]
```
> 我也是报错，梯子开全局模式也是不能用，之前一直能用的
> 
> [-]Connect Failed! Please check your Proxy or Network!
> [-]HTTPSConnectionPool(host='www.fanbus.us', port=443): Read timed out. (read timeout=10)
> [-]Connect retry 3/3
> [-]Connect Failed! Please check your Proxy or Network!
> [-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=10)
> [-]Connect retry 3/3
> [-]Connect Failed! Please check your Proxy or Network!
> [-]HTTPSConnectionPool(host='www.javbus.com', port=443): Read timed out. (read timeout=10)
> [-]Connect retry 3/3
> [-]Connect Failed! Please check your Proxy or Network!
> [-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=10)
> [-]Connect retry 3/3
> [-]Connect Failed! Please check your Proxy or Network!
> [-]HTTPSConnectionPool(host='www.javbus.com', port=443): Read timed out. (read timeout=10)
```
我也是這樣，每都要retry 3次報錯，但最後還是能成功，只是太浪費時間了

**Comment by zisu1115** [comment]
挂全局的，把设置中的代理注释掉就行了
[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
;switch=0
;type=socks5
;proxy=127.0.0.1:1080
;timeout=10
;retry=3
;cacert_file=

**Comment by Metalism666** [comment]
> 挂全局的，把设置中的代理注释掉就行了
> [proxy]
> ;proxytype: http or socks5 or socks5h switch: 0 1
> ;switch=0
> ;type=socks5
> ;proxy=127.0.0.1:1080
> ;timeout=10
> ;retry=3
> ;cacert_file=

是指把代理设置关闭吗？“switch=0“
我之前一直是这样的，也是报错，我没有更改过相关设置

**Comment by zisu1115** [comment]
> > 挂全局的，把设置中的代理注释掉就行了
> > [proxy]
> > ;proxytype: http or socks5 or socks5h switch: 0 1
> > ;switch=0
> > ;type=socks5
> > ;proxy=127.0.0.1:1080
> > ;timeout=10
> > ;retry=3
> > ;cacert_file=
> 
> 是指把代理设置关闭吗？“switch=0“
> 我之前一直是这样的，也是报错，我没有更改过相关设置

我之前并没有使用过这个软件，但是根据他的错误提示Connect Failed! Please check your Proxy or Network!这是没有连接，如果是在墙内，那就是没有连接到代理，而我是路由器直接全局的，所以不应该存在这个问题，所以就是代理错误了，我要做的就是需要让软件不要去连接代理，直连就可以了
我不清楚这个开关是什么意思，我并没有用到，所以我把所有的代码都注释掉，软件就没有去检查代理，就可以连接上了
根据自己的实际情况去选择代理的方式就好

**Comment by ftlcxj** [comment]
这个项目有Mac版本的吗？


发自我的iPhone

**Comment by Metalism666** [comment]
> > > 挂全局的，把设置中的代理注释掉就行了
> > > [proxy]
> > > ;proxytype: http or socks5 or socks5h switch: 0 1
> > > ;switch=0
> > > ;type=socks5
> > > ;proxy=127.0.0.1:1080
> > > ;timeout=10
> > > ;retry=3
> > > ;cacert_file=
> > 
> > 
> > 是指把代理设置关闭吗？“switch=0“
> > 我之前一直是这样的，也是报错，我没有更改过相关设置
> 
> 我之前并没有使用过这个软件，但是根据他的错误提示Connect Failed! Please check your Proxy or Network!这是没有连接，如果是在墙内，那就是没有连接到代理，而我是路由器直接全局的，所以不应该存在这个问题，所以就是代理错误了，我要做的就是需要让软件不要去连接代理，直连就可以了
> 我不清楚这个开关是什么意思，我并没有用到，所以我把所有的代码都注释掉，软件就没有去检查代理，就可以连接上了
> 根据自己的实际情况去选择代理的方式就好

上头有个不用翻墙的台湾用户也和我一样的情况，估计是刮削源网站自己抽风了

**Comment by cascadahk** [comment]
我暫時只能把retry次數設為1
不然每次retry3次太浪費時間，反正他retry1次也可以正常擷取，但好像不能設為0

**Comment by cascadahk** [comment]
只能退回舊版，4.6.8好像能正常工作

**Comment by LeoMonkey** [comment]
我的也是，switch选0或1都不行，而且javdb的也不知道怎么就连不上了，明明整个路由器都已经翻墙了

**Comment by yoshiko2** [comment]
用socks5h或者http

**Comment by LeoMonkey** [comment]
> 

这是Debug模式的日志：
[*]======================================================
[!]                - 25.0% [1/4] -             15:43:43
[!] [259LUXU-005] As Number making data for 'E:\Downloads\115\FC2\259LUXU-005.mp4'
[+]select javdb
[!]javdb:select site javdb32
list index out of range
[!]javdb:select site javdb32
list index out of range
list index out of range
cannot unpack non-iterable NoneType object
404 page not found
404 page not found
list index out of range
number not found
[-]Connect retry 1/3
[-]get_html_by_scraper() failed. HTTPSConnectionPool(host='javdb32.com', port=443): Max retries exceeded with url: /search?q=259LUXU-005&f=all (Caused by ResponseError('too many 503 error responses'))
cannot unpack non-iterable NoneType object
[-]get_html_by_scraper() failed. HTTPSConnectionPool(host='javdb32.com', port=443): Max retries exceeded with url: /search?q=259LUXU-005&f=all (Caused by ResponseError('too many 503 error responses'))
cannot unpack non-iterable NoneType object
[+]select fc2
list index out of range
[+]select javbus
[-]Connect retry 2/3
404 page not found
[+]select airav
404 page not found
list index out of range
[+]select fanza
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=5)
can only parse strings
[+]select xcity
list index out of range
[+]select avsox
number not found
[+]select dlsite
list index out of range
[+]select carib
cannot unpack non-iterable NoneType object
[+]select fc2club
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=5)
can only parse strings
[-]Movie number has changed! [259LUXU-005]->[None]
'[-]Move to Failed output folder, see 'E:\Downloads\115\failed\where_was_i_before_being_moved.txt'


这是config的设置：
[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=0
type=socks5h
proxy=127.0.0.1:1080
timeout=5
retry=3
cacert_file=


不知道是什么原因，一直连不上javdb，而且一直提示代理错误，我都把代理的开关关了。路由翻墙的情况下，电脑网页也可以直接访问网站了
