### ISSUE TITLE
程序无法连接到github

### ISSUE THREAD

**Issue by KIC9832227** [yoshiko2/Movie_Data_Capture#853]
[*]================= Movie Data Capture =================
[*]                        6.2.2                         
[*]======================================================
[*] - Windows-10-10.0.22622-SP0 
[*] - AMD64 - Python-3.9.13
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-08-09 23:56:58
[+]Load Config file '\\M78\video2\adout\config.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[-]Connect retry 1/3
[-]Connect retry 1/3
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 2/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please Check your proxy config
[-]Connect retry 3/3
[-]Connect Failed! Please Check your proxy config
[-]Connect retry 3/3
[-]Connect Failed! Please Check your proxy config
[!] ==================== ERROR ====================
[!]          Mapping Table Download FAILED         
[!]                    无法连接github                  
[!]                     请过几小时再试试                   
[!] Connect Failed
[-]      ------ AUTO EXIT AFTER 30s !!! ------     

全局代理已经开启，其他外网网站都能正常打开，节点也更换好多个，依旧出现错误

**Comment by a8500830** [comment]
啊一样的，路由器端走的代理

**Comment by mela93** [comment]
把自动检查更新关了，
```
[update]
update_check=0 
```

**Comment by jyh9521** [comment]
同，我很确信网络没任何问题。

**Comment by mela93** [comment]
> 同，我很确信网络没任何问题。

可以试试在配置里把proxy开启来或者关掉，之前有个版本是要开了才能连上，后来才修复，试试看吧

```
[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=0
type=socks5h
proxy=127.0.0.1:1080
timeout=20
retry=3
cacert_file=
```

**Comment by jyh9521** [comment]
> > 同，我很确信网络没任何问题。
> 
> 可以试试在配置里把proxy开启来或者关掉，之前有个版本是要开了才能连上，后来才修复，试试看吧
> 
> ```
> [proxy]
> ;proxytype: http or socks5 or socks5h switch: 0 1
> switch=0
> type=socks5h
> proxy=127.0.0.1:1080
> timeout=20
> retry=3
> cacert_file=
> ```

=_,=打开了还是不行……

**Comment by LargaRisen** [comment]
之前是可以的，突然就不行了，是因为GitHub连接有改动吗

**Comment by LargaRisen** [comment]
[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_actor.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EB038A0F70>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/c_number.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EB03889E50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_info.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EB038A06A0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by LargaRisen** [comment]
> > > 同，我很确信网络没任何问题。
> > 
> > 
> > 可以试试在配置里把proxy开启来或者关掉，之前有个版本是要开了才能连上，后来才修复，试试看吧
> > ```
> > [proxy]
> > ;proxytype: http or socks5 or socks5h switch: 0 1
> > switch=0
> > type=socks5h
> > proxy=127.0.0.1:1080
> > timeout=20
> > retry=3
> > cacert_file=
> > ```
> 
> =_,=打开了还是不行……提示无法连接到github，关闭更新检测也不行……版本是最新的。

我刚开始也遇到了，目前已解决。
打开代理设置，并修改端口号为你的梯子使用的端口
`[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=1
type=socks5h
proxy=127.0.0.1:2222
timeout=20
retry=3
cacert_file=`

**Comment by LargaRisen** [comment]
> > > 同，我很确信网络没任何问题。
> > 
> > 
> > 可以试试在配置里把proxy开启来或者关掉，之前有个版本是要开了才能连上，后来才修复，试试看吧
> > ```
> > [proxy]
> > ;proxytype: http or socks5 or socks5h switch: 0 1
> > switch=0
> > type=socks5h
> > proxy=127.0.0.1:1080
> > timeout=20
> > retry=3
> > cacert_file=
> > ```
> 
> =_,=打开了还是不行……提示无法连接到github，关闭更新检测也不行……版本是最新的。

我刚开始也遇到了，目前已解决。
**打开代理设置，并修改端口号为你的梯子使用的端口**
```
[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=1
type=socks5h
proxy=127.0.0.1:2222
timeout=20
retry=3
cacert_file=
```

**Comment by jyh9521** [comment]
> > > > 同，我很确信网络没任何问题。
> > > 
> > > 
> > > 可以试试在配置里把proxy开启来或者关掉，之前有个版本是要开了才能连上，后来才修复，试试看吧
> > > ```
> > > [proxy]
> > > ;proxytype: http or socks5 or socks5h switch: 0 1
> > > switch=0
> > > type=socks5h
> > > proxy=127.0.0.1:1080
> > > timeout=20
> > > retry=3
> > > cacert_file=
> > > ```
> > 
> > 
> > =_,=打开了还是不行……提示无法连接到github，关闭更新检测也不行……版本是最新的。
> 
> 我刚开始也遇到了，目前已解决。 **打开代理设置，并修改端口号为你的梯子使用的端口**
> 
> ```
> [proxy]
> ;proxytype: http or socks5 or socks5h switch: 0 1
> switch=1
> type=socks5h
> proxy=127.0.0.1:2222
> timeout=20
> retry=3
> cacert_file=
> ```

我是在路由器上挂的openclash，所以没有type或者端口号之类的。

**Comment by mela93** [comment]
> > > > > 同，我很确信网络没任何问题。
> > > > 
> > > > 
> > > > 可以试试在配置里把proxy开启来或者关掉，之前有个版本是要开了才能连上，后来才修复，试试看吧
> > > > ```
> > > > [proxy]
> > > > ;proxytype: http or socks5 or socks5h switch: 0 1
> > > > switch=0
> > > > type=socks5h
> > > > proxy=127.0.0.1:1080
> > > > timeout=20
> > > > retry=3
> > > > cacert_file=
> > > > ```
> > > 
> > > 
> > > =_,=打开了还是不行……提示无法连接到github，关闭更新检测也不行……版本是最新的。
> > 
> > 
> > 我刚开始也遇到了，目前已解决。 **打开代理设置，并修改端口号为你的梯子使用的端口**
> > ```
> > [proxy]
> > ;proxytype: http or socks5 or socks5h switch: 0 1
> > switch=1
> > type=socks5h
> > proxy=127.0.0.1:2222
> > timeout=20
> > retry=3
> > cacert_file=
> > ```
> 
> 我是在路由器上挂的openclash，所以没有type或者端口号之类的。

全局设置里找找看？

**Comment by UnicornK** [comment]
> 



> [_]================= Movie Data Capture ================= [_] 6.2.2 [_]====================================================== [_] - Windows-10-10.0.22622-SP0 [_] - AMD64 - Python-3.9.13 [_]====================================================== [_] - 严禁在墙内宣传本项目 - [_]====================================================== [+]Start at 2022-08-09 23:56:58 [+]Load Config file '\M78\video2\adout\config.ini'. [+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30 [-]Connect retry 1/3 [-]Connect retry 1/3 [-]Connect retry 1/3 [-]Connect retry 2/3 [-]Connect retry 2/3 [-]Connect retry 2/3 [-]Connect retry 3/3 [-]Connect Failed! Please Check your proxy config [-]Connect retry 3/3 [-]Connect Failed! Please Check your proxy config [-]Connect retry 3/3 [-]Connect Failed! Please Check your proxy config [!] ==================== ERROR ==================== [!] Mapping Table Download FAILED [!] 无法连接github [!] 请过几小时再试试 [!] Connect Failed [-] ------ AUTO EXIT AFTER 30s !!! ------
> 
> 全局代理已经开启，其他外网网站都能正常打开，节点也更换好多个，依旧出现错误

我也遇到你这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用

**Comment by UnicornK** [comment]
我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用

**Comment by mela93** [comment]
试试看最新的版本，作者已经更新到6.3.1版本了，我目前用的都正常

**Comment by jyh9521** [comment]
> 我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用

确实如此，没想过所有网站都可以访问就raw有问题这个方面，解决之后就可以用了。

**Comment by Chinsll** [comment]
> > 我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用
> 
> 确实如此，没想过所有网站都可以访问就raw有问题这个方面，解决之后就可以用了。

我也是这个问题，请问怎么解决的，我是docker版本。

**Comment by jyh9521** [comment]
> > > 我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用
> > 
> > 
> > 确实如此，没想过所有网站都可以访问就raw有问题这个方面，解决之后就可以用了。
> 
> 我也是这个问题，请问怎么解决的，我是docker版本。

只要解决https://raw.githubusercontent.com/无法访问的问题就可以了。

**Comment by UnicornK** [comment]
> > > 我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用
> > 
> > 
> > 确实如此，没想过所有网站都可以访问就raw有问题这个方面，解决之后就可以用了。
> 
> 我也是这个问题，请问怎么解决的，我是docker版本。

你在创建docker版时候加上这个参数--add-host=raw.Githubusercontent.com:185.199.108.133

**Comment by Chinsll** [comment]
> > > > 我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用
> > > 
> > > 
> > > 确实如此，没想过所有网站都可以访问就raw有问题这个方面，解决之后就可以用了。
> > 
> > 
> > 我也是这个问题，请问怎么解决的，我是docker版本。
> 
> 你在创建docker版时候加上这个参数--add-host=raw.Githubusercontent.com:185.199.108.133

[*]================= Movie Data Capture =================[*]                        6.2.2                         [*]======================================================[*] - Linux-5.8.18-z4-generic+-x86_64-with [*] - x86_64 - Python-3.9.13[*]======================================================[*] - 严禁在墙内宣传本项目 - [*]======================================================[+]Start at 2022-09-03 10:04:12[+]Load Config file '/config/mdc.ini'.[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30[*]                 * New update 6.3.1 *                 [*]                     ↓ Download ↓                     [*]https://github.com/yoshiko2/Movie_Data_Capture/releases[*]======================================================[-]Connect retry 1/3[-]Connect retry 1/3[-]Connect retry 1/3[-]Connect retry 2/3[-]Connect retry 2/3[-]Connect retry 2/3[-]Connect retry 3/3[-]Connect retry 3/3[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_actor.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f43262fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_info.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f432622e0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![-]Connect retry 3/3[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/c_number.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f4325b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![!] ==================== ERROR ====================[!]          Mapping Table Download FAILED         [!]                    无法连接github                  [!]                     请过几小时再试试                   [!] Connect Failed[-]      ------ AUTO EXIT AFTER 30s !!! ------     

还是不行，能帮忙看下这个日志，问题在哪吗？

**Comment by UnicornK** [comment]
> > > > > 我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用
> > > > 
> > > > 
> > > > 确实如此，没想过所有网站都可以访问就raw有问题这个方面，解决之后就可以用了。
> > > 
> > > 
> > > 我也是这个问题，请问怎么解决的，我是docker版本。
> > 
> > 
> > 你在创建docker版时候加上这个参数--add-host=raw.Githubusercontent.com:185.199.108.133
> 
> [_]================= Movie Data Capture =================[_] 6.2.2 [_]======================================================[_] - Linux-5.8.18-z4-generic+-x86_64-with [_] - x86_64 - Python-3.9.13[_]======================================================[_] - 严禁在墙内宣传本项目 - [_]======================================================[+]Start at 2022-09-03 10:04:12[+]Load Config file '/config/mdc.ini'.[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30[_] * New update 6.3.1 * [_] ↓ Download ↓ [*][https://github.com/yoshiko2/Movie_Data_Capture/releases[*]======================================================[-]Connect](https://github.com/yoshiko2/Movie_Data_Capture/releases%5B*%5D======================================================%5B-%5DConnect) retry 1/3[-]Connect retry 1/3[-]Connect retry 1/3[-]Connect retry 2/3[-]Connect retry 2/3[-]Connect retry 2/3[-]Connect retry 3/3[-]Connect retry 3/3[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_actor.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f43262fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_info.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f432622e0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![-]Connect retry 3/3[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/c_number.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f4325b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![!] ==================== ERROR ====================[!] Mapping Table Download FAILED [!] 无法连接github [!] 请过几小时再试试 [!] Connect Failed[-] ------ AUTO EXIT AFTER 30s !!! ------
> 
> 还是不行，能帮忙看下这个日志，问题在哪吗？

你本地是否能ping通raw.Githubusercontent.com，然后进容器里面看是否ping通raw.Githubusercontent.com这个地址

**Comment by Chinsll** [comment]
> > > > > > 我也遇到这种情况，我这边发现是raw.Githubusercontent.com这个地址没有解析到，hosts指定IP地址就可以正常使用
> > > > > 
> > > > > 
> > > > > 确实如此，没想过所有网站都可以访问就raw有问题这个方面，解决之后就可以用了。
> > > > 
> > > > 
> > > > 我也是这个问题，请问怎么解决的，我是docker版本。
> > > 
> > > 
> > > 你在创建docker版时候加上这个参数--add-host=raw.Githubusercontent.com:185.199.108.133
> > 
> > 
> > [_]================= Movie Data Capture =================[_] 6.2.2 [_]======================================================[_] - Linux-5.8.18-z4-generic+-x86_64-with [_] - x86_64 - Python-3.9.13[_]======================================================[_] - 严禁在墙内宣传本项目 - [_]======================================================[+]Start at 2022-09-03 10:04:12[+]Load Config file '/config/mdc.ini'.[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30[_] * New update 6.3.1 * [_] ↓ Download ↓ [*][https://github.com/yoshiko2/Movie_Data_Capture/releases[*]======================================================[-]Connect](https://github.com/yoshiko2/Movie_Data_Capture/releases%5B*%5D======================================================%5B-%5DConnect) retry 1/3[-]Connect retry 1/3[-]Connect retry 1/3[-]Connect retry 2/3[-]Connect retry 2/3[-]Connect retry 2/3[-]Connect retry 3/3[-]Connect retry 3/3[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_actor.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f43262fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_info.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f432622e0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![-]Connect retry 3/3[-]HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /yoshiko2/Movie_Data_Capture/master/MappingTable/c_number.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0f4325b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))[-]Connect Failed! Please check your Proxy or Network![!] ==================== ERROR ====================[!] Mapping Table Download FAILED [!] 无法连接github [!] 请过几小时再试试 [!] Connect Failed[-] ------ AUTO EXIT AFTER 30s !!! ------
> > 还是不行，能帮忙看下这个日志，问题在哪吗？
> 
> 你本地是否能ping通raw.Githubusercontent.com，然后进容器里面看是否ping通raw.Githubusercontent.com这个地址

可以ping的通。
![Screenshot_2022-09-03-11-44-17-14_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91552281/188254594-e3d290f8-6a22-4cf7-be49-8091045a0db5.jpg)

**Comment by zmharuna123** [comment]
我也是这个问题

**Comment by waltcow** [comment]
docker 版本遇到同样的问题
